### ISSUE TITLE
Améliorations de l'OS (kernel cpcdos)

### ISSUE THREAD

**Issue by caillou15** [GeomTechDEV/GTOS#1]
Toute amélioration est la bienvenue car l'OS est quasiment vide

**Comment by caillou15** [comment]
ça avance pas 
😕😲😪😥😦😫😖😩🙅👎

**Comment by caillou15** [comment]
Il n'y a rien à part la barre des tâches

**Comment by geomtech** [comment]
Le projet est en stand-bye, désolé.
